app = "nos-gpu"
primary_region = "ord"
vm.size = "l40s"
swap_size_mb = 32768

[build]
image = "autonomi/nos:0.2.1-gpu"

[experimental]
  entrypoint = ["/app/entrypoint.sh", "--http"]

[env]
  NOS_HOME = "nos"

[mounts]
  source = "nos"
  destination = "/root/.nosd"
  initial_size = "100gb"

[http_service]
  internal_port = 8000
  protocol = "tcp"
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
