app = "nos-cpu"
primary_region = "ord"

[build]
image = "autonomi/nos:latest-cpu"

[env]
  NOS_HOME = "nos"

[mounts]
source = "nos"
destination = "/root/.nosd"

[http_service]
internal_port = 50051
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 1
processes = ["app"]
